- share/README.md
- share/pom.xml
- share/src/main/java/io/zensoft/share/SharingMicroServiceApplication.java
- share/src/main/java/io/zensoft/share/config/RabbitMQConfiguration.java
- share/src/main/java/io/zensoft/share/listener/PostListener.java
- share/src/main/java/io/zensoft/share/model/PostDto.java
- share/src/main/java/io/zensoft/share/model/PostResponseDto.java
- share/src/main/java/io/zensoft/share/model/PostServiceType.java
- share/src/main/java/io/zensoft/share/model/PostStatus.java
- share/src/main/java/io/zensoft/share/repository/PostDtoRepository.java
- share/src/main/java/io/zensoft/share/repository/PostResponseRepository.java
- share/src/main/java/io/zensoft/share/service/BasePublisherService.java
- share/src/main/java/io/zensoft/share/service/HttpHelper.java
- share/src/main/java/io/zensoft/share/service/PublisherService.java
- share/src/main/resources/application.properties
> Java initial with edited pom.xml

- python/apps/candidates/urls.py
- python/apps/departments/urls.py
- python/apps/evaluations/urls.py
- python/apps/interviews/urls.py
- python/apps/requests/urls.py
- python/apps/users/urls.py
- python/apps/vacancies/urls.py
- python/urls.py
* Add url file into every app
* Update global url file
> Update global urls file

- Android/ZensoftHRCRM/.idea/misc.xml
- Android/ZensoftHRCRM/app/build.gradle
- Android/ZensoftHRCRM/app/src/debug/assets/mock.api/all_candidates.json
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/MainActivity.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/data/entity/Comment.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/data/network/candidates/CandidatesRepository.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidatesList/CandidatesAdapter.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidatesList/CandidatesContract.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidatesList/CandidatesFragment.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidatesList/CandidatesPresenter.java
- Android/ZensoftHRCRM/app/src/main/res/layout/candidate_item.xml
- Android/ZensoftHRCRM/app/src/main/res/layout/fragment_candidates_list.xml
*Create basic contract
*Create basic fragment, presenter and repository
*Create layout for candidate item in list
*all_candidates json file simplified for testing
> Android. Initial ui for candidate list

- share/pom.xml
- share/src/main/java/io/zensoft/share/aspect/PostListenerPointCut.java
- share/src/main/java/io/zensoft/share/aspect/log/PostListenerLoggingAdvice.java
- share/src/main/java/io/zensoft/share/config/log/LoggingConfiguration.java
Add logger to share microservice
*used Spring AOP for logging
*logs incoming requests to rabbitmq queues that
publishes
*logs:
-queue name
-queue message body
-class,method detail that handles queues
*created classes:
-added class LoggingConfiguration
-added class PostListenerPointCut
-added class PostListenerLoggingAdvice
-added Spring Boot AOP dependency to pom.xml
> Java add logger to incoming rabbitmq requests from monolith

- python/apps/evaluations/serializers.py
- python/apps/evaluations/urls.py
- python/apps/evaluations/views.py
> Python. Create a new criteria and retrieve a list of criterias

- python/apps/candidates/models.py
- python/apps/candidates/serializers.py
- python/apps/candidates/urls.py
- python/apps/candidates/views.py
Add new serializer on comments and add endpoint comments/, and add class view for create comment.
> Python. Create comments

- python/apps/requests/serializer.py
- python/apps/requests/urls.py
- python/apps/requests/views.py
* Add request update
* Add request detail
* Add /request/id endpoint to urls
> Python. Add request detail

- python/apps/candidates/serializers.py
> Python. Fix Candidates GET Endpoint:

- NestJS/ormconfig.template.json
- NestJS/src/Messages/message.entity.ts
- NestJS/src/Messages/message.listener.ts
- NestJS/src/Templates/template.entity.ts
- NestJS/src/Templates/template.listener.ts
- NestJS/src/Templates/template.module.ts
- NestJS/src/main.ts
Get a task from RabbitMQ and create a template, save to database
> Create template from task of RabbitMQ

- python/config/base.py
- python/config/pagination.py
- python/requirements.txt
* Add pagination.py with custom pagination class
* Add rest framework default pagination class
* Add django filters to installed apps/requirements
> Python. Add pagination to all enpoints retrieving list

- Android/ZensoftHRCRM/.gitignore
- Android/ZensoftHRCRM/app/build.gradle
- Android/ZensoftHRCRM/app/src/debug/assets/mock.api/all_candidates.json
- Android/ZensoftHRCRM/app/src/main/AndroidManifest.xml
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/MainActivity.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/data/network/candidates/CandidatesRepository.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidateDetail/CandidateDetail.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidateDetail/CandidateDetailContract.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidateDetail/CandidateDetailFragment.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidateDetail/CandidateDetailPresenter.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidatesList/CandidatesAdapter.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidatesList/CandidatesContract.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidatesList/CandidatesFragment.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidatesList/CandidatesPresenter.java
- Android/ZensoftHRCRM/app/src/main/res/drawable/ic_email_black.xml
- Android/ZensoftHRCRM/app/src/main/res/drawable/ic_phone_black.xml
- Android/ZensoftHRCRM/app/src/main/res/layout/activity_candidate_detail.xml
- Android/ZensoftHRCRM/app/src/main/res/layout/content_main.xml
- Android/ZensoftHRCRM/app/src/main/res/layout/fragment_candidate_detail.xml
- Android/ZensoftHRCRM/app/src/main/res/layout/fragment_candidates_list.xml
- Android/ZensoftHRCRM/app/src/main/res/values/strings.xml
*display candidate items in recycler view using local json file to
emulate server response
*basic Presenter, View created for CandidateDetail
> Android. Display list of candidates based on fake response from json file.

- Android/ZensoftHRCRM/app/src/debug/assets/mock.api/candidate_detail.json
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/data/entity/Candidate.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/data/entity/CandidateInterviewItem.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/data/entity/Comment.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/data/entity/Cv.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/data/network/candidates/CandidatesRepository.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/data/network/test/RestServiceTest.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidateDetail/CandidateDetailFragment.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidateDetail/CandidateDetailPresenter.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidatesList/CandidatesPresenter.java
- Android/ZensoftHRCRM/app/src/main/res/drawable/ic_attach_file.xml
- Android/ZensoftHRCRM/app/src/main/res/layout/cd_comment_item.xml
- Android/ZensoftHRCRM/app/src/main/res/layout/cd_cvs_item.xml
- Android/ZensoftHRCRM/app/src/main/res/layout/cd_interview_item.xml
- Android/ZensoftHRCRM/app/src/main/res/layout/fragment_candidate_detail.xml
- Android/ZensoftHRCRM/app/src/main/res/values/colors.xml
- Android/ZensoftHRCRM/app/src/main/res/values/dimens.xml
- Android/ZensoftHRCRM/app/src/main/res/values/strings.xml
*created new json file to emulate server response
*Candidate entity was modified due to api specs changes
*Display Candidate detailed info in new activity
> Android. Display candidate detailed info based on fake response

- python/config/base.py
change config ALLOWED_HOSTS variable.
> Python. Fix allowed host

- python/apps/candidates/serializers.py
- python/apps/candidates/tests.py
- python/apps/candidates/views.py
- python/apps/interviews/serializers.py
- python/apps/interviews/urls.py
- python/apps/interviews/views.py
There was no detailed view for interview
* Add Interview detail serializer
* Add Interviewer detail serializer for detailed info
* Add Interviewer serializer
* Add evaluation serializer
* Move candidate serializer to interview app
> Python. Interview detail view

- python/apps/interviews/serializers.py
Change `InterviewerSerializer` in `AuxInterviewSerializer`
> Python. Fix candidate detail view

- python/apps/interviews/serializers.py
- python/apps/interviews/urls.py
- python/apps/interviews/views.py
* Change `InterviewListView` to `InterviewListCreateView`
* Add `InterviewCreateSerializer`
* Override `create` method for both view and serializer
> Python. Interview create view

- python/apps/templates/admin.py
- python/apps/templates/serializers.py
- python/apps/templates/urls.py
- python/apps/templates/views.py
* create 3 new seralizers: TemplateCreateSerializer, TemplateDetailSerializer, AttachmentSerializer. 
* override create method in TemplateListCreateView
* create new class AttachmentListCreateView
* add AttachmentListCreateView to path in urls.py
* register Attachment model in admin.py
> Python. Add post request to create new template and attachment

- python/apps/interviews/serializers.py
- python/apps/interviews/views.py
Used sets to get the interviewers that we need to delete and create. Without sets it would cost us O(N^2).
> Python. Interview update view

- Android/ZensoftHRCRM/app/src/main/AndroidManifest.xml
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidateDetail/CandidateDetailContract.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidateDetail/CandidateDetailFragment.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidateDetail/CandidateDetailPresenter.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidateDetail/CommentsAdapter.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidateDetail/CvsAdapter.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/candidates/candidateDetail/InterviewsAdapter.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/interviews/createInterview/CreateInterview.java
- Android/ZensoftHRCRM/app/src/main/java/com/erkprog/zensofthrcrm/ui/interviews/createInterview/CreateInterviewFragment.java
- Android/ZensoftHRCRM/app/src/main/res/drawable/ic_add_circle.xml
- Android/ZensoftHRCRM/app/src/main/res/layout/activity_create_interview.xml
- Android/ZensoftHRCRM/app/src/main/res/layout/cd_action_buttons.xml
- Android/ZensoftHRCRM/app/src/main/res/layout/fragment_create_interview.xml
- Android/ZensoftHRCRM/app/src/main/res/values/strings.xml
*create layouts
*new Activity to create interview
*on click listener implemented for InterviewButton in candidate profile
> Android. Create Interview Event

- share/src/main/java/io/zensoft/share/dto/RequirementDto.java
- share/src/main/java/io/zensoft/share/dto/VacancyDto.java
- share/src/main/java/io/zensoft/share/dto/VacancyResponseDto.java
- share/src/main/java/io/zensoft/share/model/PublisherServiceType.java
- share/src/main/java/io/zensoft/share/model/Requirement.java
- share/src/main/java/io/zensoft/share/model/Vacancy.java
- share/src/main/java/io/zensoft/share/service/converter/DefaultVacancyConverterService.java
- share/src/main/java/io/zensoft/share/service/converter/DefaultVacancyResponseConverterService.java
* wrote implementation to dto converters
* added final dto standards
> Java. Write implementation to dto converters

- NestJS/.dockerignore
- NestJS/Dockerfile
- NestJS/docker-compose.yml
- NestJS/src/Messages/message.listener.ts
- NestJS/src/app.module.ts
Created Dockerfile and docker-compose.yml to link app container and db postgres container.
> NestJS. Dockerized NestJS application. Dockerfile and docker-compose.

- share/src/main/java/io/zensoft/share/service/PublisherManagerService.java
- share/src/main/java/io/zensoft/share/service/PublisherService.java
modify PublisherService class
add getInfo() method
change methods' response types
change methods' arguments
add PublisherManagerService class
> Java. modify class for latest architecture changes

- python/.gitignore
- python/Dockerfile
- python/config/nginx/nginx.conf
- python/config/production.py
- python/docker-compose.yml
* Add nginx config for local development
* Update docker-compose
* Update Dockerfile
* Update .gitignore
* Update production config
> Python. Dockerize django application

- share/src/main/java/io/zensoft/share/repository/VacancyResponseRepository.java
- share/src/main/java/io/zensoft/share/service/model/VacancyResponseModelService.java
- share/src/main/java/io/zensoft/share/service/model/impl/DefaultVacancyResponseModelService.java
* added method that gets VacancyResponse by Vacancy and PublisherServiceType (to respond to monolith)
* added method that gets all VacancyResponse by Vacancy
> Java. add repository and model service methods

- share/src/main/java/io/zensoft/share/listener/Facebook/FacebookListener.java
- share/src/main/java/io/zensoft/share/service/Facebook/FacebookPublisherManagerService.java
- share/src/main/java/io/zensoft/share/service/Facebook/FacebookPublisherService.java
add implementation of the publishing to Facebook
add FacebookListener
add FacebookPublisherManagerService
bind FacebookPublisherService with architecture
> Java. Implement Listener and Manager for Facebook; bind FacebookPublisherService with them

- python/docker-compose.yml
- python/wait_for_pg.py
* Add wait_for_pg script to make it not crash, when postgres is not yet ready
> Python. Fix bug with not adding staticfiles to volume

- python/config/base.py
Fixed a bug when entering the admin panel.
> Python. Change CSRF_COOKIE_SECURE value on False

- python/apps/fixtures/vacancies.json
- python/apps/vacancies/models.py
> Python. Ticket - Fix fixtures

- share/pom.xml
- share/src/main/java/io/zensoft/share/dto/VacancyDto.java
- share/src/main/java/io/zensoft/share/model/Vacancy.java
- share/src/main/java/io/zensoft/share/service/converter/DefaultVacancyConverterService.java
- share/src/main/java/io/zensoft/share/service/facebook/FacebookPublisherManagerService.java
- share/src/main/java/io/zensoft/share/service/facebook/FacebookPublisherService.java
add access_token field to DTO
update FacebookPublisherService
add check if image url is valid
add check if page is valid
change package name to uppercase
> Java. Add access_token field to DTO, update FacebookPublisherService, add checks for validities, fix typo

- python/apps/candidates/urls.py
- python/apps/departments/urls.py
- python/apps/interviews/urls.py
- python/apps/notifications/urls.py
- python/apps/requests/urls.py
- python/apps/templates/urls.py
- python/apps/users/urls.py
- python/apps/vacancies/urls.py
- python/urls.py
Need to change to fix all tests
> Python. Change all endpoints apps

- python/apps/utils/rabbitmq.py
* send requests to js-microservice through rabbitmq
* receive responses from js-microservice through rabbitmq
> Python. Fix apps/utils/rabbitmq.py

- FrontJS/package-lock.json
- FrontJS/src/components/containers/head/CreatePositionContainer.jsx
- FrontJS/src/components/ui/MultiSelection.jsx
- FrontJS/src/components/ui/SelectList.jsx
- FrontJS/src/components/ui/TextArea.jsx
- FrontJS/src/scenes/head/OpenedPositions.js
head of Department
* post and get requests in Create position
* get request Opened positios
* deletion of positoins
> FrontJS get post request headOfDep

- FrontJS/src/components/ui/PlusMinus.jsx
* little modifications on PlusMinus file
> FrontJS: modified counting

- FrontJS/src/App.js
- FrontJS/src/scenes/pm/RequestList.js
requestList file modified , PM folder
> FrontJS: requestList PM modified

- FrontJS/src/App.js
- FrontJS/src/components/containers/hr/ListOfCandidatesContainer.jsx
- FrontJS/src/scenes/pm/RequestList.js
- FrontJS/src/utils/DateConvert.js
Here you are Date convert file in Utils folder
> FrontJS: date convert in utils

- FrontJS/src/App.js
- FrontJS/src/components/containers/head/CreatePositionContainer.jsx
- FrontJS/src/components/containers/hr/ListOfCandidatesContainer.jsx
- FrontJS/src/components/ui/MultiSelection.jsx
- FrontJS/src/scenes/interviewer/ListInterview.js
- FrontJS/src/utils/urls.js
* getting data from api and populating table list in ListInterview.js
* a few modifications in CreatePositionContainer file
> FrontJS: fetch data Listinterviews.js

- python/apps/templates/urls.py
- python/apps/templates/views.py
- python/apps/utils/rabbitmq.py
- python/config/base.py
* add TemplateDetailView, add thit view to urls
* add binding of queue of receiving responses in rabbitmq.py
* add new constants: RABBITMQ_USERNAME, RABBITMQ_PASSWORD in base.py
* rewrite views with rest_framework.views.APIView
> Python. Edit template's views, rabbitmq.py, base.py

- share/src/main/java/io/zensoft/share/config/rabbitmq/RabbitMqComponentDeclarationConfiguration.java
- share/src/main/java/io/zensoft/share/config/rabbitmq/RabbitMqConnectionConfiguration.java
- share/src/main/java/io/zensoft/share/config/rabbitmq/RabbitMqExchangeBindingConfiguration.java
- share/src/main/java/io/zensoft/share/service/VacancyResponseSenderService.java
- share/src/main/resources/application.properties
declare some variable in configuration file to be able to set their value environment variable from docker
and access those variables from `@Configuration` classes
> Java.preparations for docker

- share/pom.xml
- share/src/main/java/io/zensoft/share/service/facebook/FacebookConfigs.java
- share/src/main/java/io/zensoft/share/service/facebook/FacebookPublisherService.java
Add FacebookConfigs class
Inject it in FacebookPublisherService
Rearrange methods - public methods first
> Java. Add FacebookConfigs class, inject it in FacebookPublisherService

- share/src/main/java/io/zensoft/share/service/facebook/FacebookPublisherService.java
- share/src/main/java/io/zensoft/share/service/facebook/FacebookUrlBuilder.java
Add FacebookUrlBuilder to delegate responsibility for building url to send requests to facebook api
Update FacebookPublisherService
> Java. Add FacebookUrlBuilder

- share/pom.xml
- share/src/main/java/io/zensoft/share/service/diesel/body/PublicationVacancyContentPreparer.java
- share/src/main/resources/templates/vacancyContentTemplate.vt
* add one class who defines variables
* add html template
* add maven dependency for template engine Apache Velocity
> Java. Add VacancyContentPreparer and tempalte for it

- share/src/main/java/io/zensoft/share/service/facebook/FacebookPublisherManagerService.java
- share/src/main/java/io/zensoft/share/service/facebook/FacebookRequestSender.java
use interfaces instead of classes
> Java. update FacebookPublisherManagerService

- share/src/main/java/io/zensoft/share/listener/jobkg/JobKgListener.java
> Java. Job.kg add listener

- FrontJS/src/components/containers/hr/EditVacancyContainer.jsx
- FrontJS/src/components/containers/hr/ListOfCandidatesContainer.jsx
- FrontJS/src/components/containers/hr/ListOfInternsContainer.jsx
- FrontJS/src/components/containers/hr/ListOfReservesContainer.jsx
- FrontJS/src/components/containers/hr/ProfileContainer.jsx
- FrontJS/src/components/ui/ModalWindow.jsx
- FrontJS/src/utils/GetStatus.js
- Get request for list of interns is done
- Added new function to init status 
- Added status to Reserve Table
- Unused variables removed
- Added placeholder for incoming CV
> FrontJS. List of interns is done

- share/src/main/java/io/zensoft/share/service/diesel/DieselPublisherManagerService.java
- share/src/main/java/io/zensoft/share/service/diesel/body/PublicationPostRequestBody.java
- share/src/main/java/io/zensoft/share/service/diesel/body/PublicationVacancyContentBuilder.java
- share/src/main/java/io/zensoft/share/service/diesel/sender/PublicationPostRequestSender.java
> Java. Add DieselPublisherManagerService

- python/apps/authentication/urls.py
- python/apps/authentication/views.py
- python/apps/users/managers.py
- python/apps/users/urls.py
- python/config/base.py
- python/urls.py
- for frontend
- role in header
- refactor urls
- move some urls into auth app
- clean settings
> Python. Create Token with Role

- share/src/main/java/io/zensoft/share/service/diesel/DieselPublisherService.java
- share/src/main/java/io/zensoft/share/service/diesel/RequestSender.java
- share/src/main/java/io/zensoft/share/service/diesel/body/LoginPostRequestBody.java
- share/src/main/java/io/zensoft/share/service/diesel/body/PublicationPostRequestBody.java
- share/src/main/java/io/zensoft/share/service/diesel/body/PublicationVacancyContentBuilder.java
- share/src/main/java/io/zensoft/share/service/diesel/header/AuthKeyHeader.java
- share/src/main/java/io/zensoft/share/service/diesel/header/PublicationHeader.java
- share/src/main/java/io/zensoft/share/service/diesel/sender/AuthKeyGetRequestSender.java
- share/src/main/java/io/zensoft/share/service/diesel/sender/LoginPostRequestSender.java
- share/src/main/java/io/zensoft/share/service/diesel/sender/PublicationPostRequestSender.java
- share/src/main/java/io/zensoft/share/service/diesel/sender/RequestResponseBuilderService.java
> Java. Add logs and RequestResponseBuilderService class

- FrontJS/src/App.js
- FrontJS/src/components/containers/head/CreatePositionContainer.jsx
- FrontJS/src/components/containers/head/EditPositionContainer.jsx
- FrontJS/src/index.css
- FrontJS/src/scenes/general/Statistics.js
- FrontJS/src/scenes/general/statistics.css
- FrontJS/src/scenes/head/OpenedPositions.js
- FrontJS/src/scenes/head/headstyle.css
Style
*  statistics
* opened positions
> FrontJS: little bit of styling

- share/src/main/java/io/zensoft/share/service/converter/DefaultRequirementConverterService.java
Added if statement that checks for null Department object when converting from dto
> Java. Dto bug fix

- share/src/main/java/io/zensoft/share/model/Vacancy.java
- share/src/main/java/io/zensoft/share/repository/VacancyRepository.java
- share/src/main/java/io/zensoft/share/repository/VacancyResponseRepository.java
- share/src/main/java/io/zensoft/share/service/DefaultVacancyRetrieverService.java
- share/src/main/java/io/zensoft/share/service/model/VacancyResponseModelService.java
- share/src/main/java/io/zensoft/share/service/model/impl/DefaultVacancyModelService.java
- share/src/main/java/io/zensoft/share/service/model/impl/DefaultVacancyResponseModelService.java
Modify `save()` method for `Vacancy` model
now it check for existence for another data in DB for given `uuid`
save to DB only if no data exists with such `uuid`
> Java. improve vacancy save() method

- python/apps/templates/views.py
* add RabbitMQ host from settings
* add returning valid http status in response of endpoints
> Python. Refactor apps/templates/views.py

- share/src/main/java/io/zensoft/share/dto/VacancyResponseDto.java
- share/src/main/java/io/zensoft/share/service/converter/DefaultVacancyResponseConverterService.java
> Java. Edited vacancy response dto and its converter

- python/apps/fixtures/db.json
add single db.json fixture(but not deleted others for safety)
`python manage.py loaddata apps/fixtures/db.json`
> Python.Fix fixtures

- share/src/main/java/io/zensoft/share/service/diesel/DieselPublisherManagerService.java
- share/src/main/java/io/zensoft/share/service/diesel/DieselPublisherService.java
- share/src/main/java/io/zensoft/share/service/diesel/body/PublicationPostRequestBody.java
* commented save() method to avoid exception. In later versions it will be changed.
> Java. Add try-catch to avoid exceptions

- share/src/main/java/io/zensoft/share/service/jobkg/JobKgPublisherManagerService.java
Removed model service save method, it throws exception
> Java. Remove save method to test
